### PR TITLE
Made xcodePreferences.js compatible with Cordova v7

### PR DESCRIPTION
**Pull request by aramando**
Fix for issue #110

### CODE REVIEW

**Comment by TianleZhang** [comment]
When can this ticket be merged to master?

**Comment by jacquesdev** [comment]
Yup, please merge this and release to npm :)

**Comment by majid701** [comment]
@nikDemyankov please merge this pull request. It's needed can't run my ios app without it!

thanks

**Comment by newuser44** [comment]
Did this get merged in?  Not sure how to tell.

**Comment by aramando** [comment]
No, it hasn't been merged, I don't know why; it seems nobody is updating this plugin at the moment. 

I would suggest just referencing this commit with the fix as your plugin source instead of the nordnet master. If you're uncomfortable relying on my repository you can always fork it and maintain your own source.

`cordova plugin add --save https://github.com/aramando/cordova-universal-links-plugin#35b3ed7e9a0310b12f1ac92a5159b21ce50eee57`

**Comment by schmidt** [comment]
I needed to add a `.git` to the Github URL, to make it work. Also `--save` seems to be the default now.

```
cordova plugin add https://github.com/aramando/cordova-universal-links-plugin.git#35b3ed7e9a0310b12f1ac92a5159b21ce50eee57
```

Other than that, I can confirm, that this change works as expected. Thanks for the help.

**Comment by florgb02** [comment]
Is there any plans on merging this PR?

**Pull request closed without merging**
