### PR TITLE
Fix for issue #110 - support for Cordova 7.0

### PR DESCRIPTION
**Pull request by martindrapeau**

### CODE REVIEW

**Comment by ccorcos** [comment]
@nikDemyankov can you take a look at this PR?

**Comment by sam2x** [comment]
Please merge this. The current code is breaking all cordova build project which want to use last cordova version. This patch is fixing it.  Thanks for it @martindrapeau

**Comment by ccorcos** [comment]
@sam2x you can just pull this branch in the meantime:

```
	<plugin name="cordova-universal-links-plugin" spec="https://github.com/nordnet/cordova-universal-links-plugin#22225179a5debfcff801e306eb1bf5477200aeda" />
```

**Comment by ccorcos** [comment]
@nikDemyankov whats taking so long?

**Review by ben-kn-app — APPROVED** [review]

**Comment by ben-kn-app** [comment]
Hi @ccorcos, I can't add your branch 

`<plugin name="cordova-universal-links-plugin" spec="https://github.com/nordnet/cordova-universal-links-plugin#22225179a5debfcff801e306eb1bf5477200aeda" />` 

it gives the following error: 
`fatal: reference is not a tree: 22225179a5debfcff801e306eb1bf5477200aeda`

Any other way to add this branch?

**Comment by ccorcos** [comment]
sorry, wrong username:

```
<plugin name="cordova-universal-links-plugin" spec="https://github.com/martindrapeau/cordova-universal-links-plugin#22225179a5debfcff801e306eb1bf5477200aeda" />
```

**Comment by ccorcos** [comment]
Lets do this @nikDemyankov

**Comment by mix3d** [comment]
Is this commit better than PR #114?

**Review by shivamkejriwal — APPROVED** [review]

**Comment by musemind** [comment]
This made me crazy working with Meteor, I had to change the file on every build when switching between branches. I forked the repo and made the changed of this pull request.

Feel free to use it `cordova-universal-links-plugin-fix@1.2.1` (-fix suffix) for a quickfix.
https://www.npmjs.com/package/cordova-universal-links-plugin-fix

**Pull request closed without merging**
