### PR TITLE
fix #133 : Manifest error with cordova 6+

### LINKED ISSUE #133: Cannot read property 'manifest' of undefined
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"

>cordova build
Android Studio project detected
(node:21980) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'manifest' of undefined
(node:21980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

>cordova platform version android
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

>cordova --version
8.0.0

>npm --version
5.6.0

>node --version
v8.9.3

### PR DESCRIPTION
**Pull request by Twister42**
Full fix for #133

### CODE REVIEW

**Comment by brnosouza** [comment]
@nordnet-release @robsan-nordnet 

We need this PR ASP... Someone cant merge it.

**Comment by Twister42** [comment]
Hi, is there somebody who can merge and release this ?
@nordnet-release @codler @FilipStenbeck @iamstarkov @johankitti @KitsuneKelso

**Comment by lougreenwood** [comment]
@Twister42 looks like this repo has been abandoned by @nordnet-release...

Happy days :(

**Comment by Twister42** [comment]
Yes. But they are still active on github, they could merge the damn stuff or give the repo :'(

**Comment by Twister42** [comment]
@nordnet-release @codler @FilipStenbeck @iamstarkov @johankitti @KitsuneKelso @bstream could smbdy at nordnet merge this repo's PR ? or give credentials on the repo so people could make it live ?

**Pull request closed without merging**
